import "Item.idl";

namespace Sample
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window,Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainWindow();
        Double V1;
        Microsoft.UI.Xaml.GridLength VV1{ get; };
        Windows.Foundation.Collections.IObservableVector<Item> TheItems{ get; };


    }
}
