namespace Sample
{
    [default_interface]
    runtimeclass StaggeredLayout : Microsoft.UI.Xaml.Controls.VirtualizingLayout
    {
        StaggeredLayout();
        Int32 ColumnCount;
        static Microsoft.UI.Xaml.DependencyProperty ColumnCountProperty{ get; };
    }
}
